APP:
  mode: run   #主程序运行模式 (debug)-(run)[debug为测试模式/run为运行模式]
  verifyMode: smtp #验证模式 (smtp)-(mx)-(regex)
  chunkSize:  5 #  分片大小  总数据除于你输入的数字
  regexConfig:  #语法验证配置项
    goroutines: 10   #并发协程量
    regex: ^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,63}$  #语法验证的正则表达式
  mxConfig:   #mx记录配置项
    mode: doh #验证模式  (doh)-(default)
    goroutines:  50 #并发协程量
    timeout: 5s  #连接超时时间
    dnsServer: ""  #dns服务器<*> [当mode为default时填写/不填写按照本机DNS解析]
  smtpConfig:
    mode:   #验证模式
    goroutines:   50  #并发协程量
    timeout:   30s  #连接超时时间
    port:  25   #发件邮箱
    keys:    #smtp验证关键词
      - unknown user
      - unknown account
      - unknown customer
      - unknown mailbox

Data: #邮箱数据处理
  path:  ./emails.txt  #邮箱数据路径
  whiteList:   ../config/white_list.txt #白名单文件路径
  blackList:   ../config/black_list.txt  #黑名单文件路径